### ISSUE TITLE
Evalulate cmake NuttX wrapper

### ISSUE THREAD

**Issue by dagar** [PX4/PX4NuttX#2]
@davids5 FYI NuttX cmake wrapper is in the cmake branch here. https://github.com/PX4/PX4NuttX/tree/cmake

 - cmake wrapper for building each nuttx lib
 - copy NuttX to build directory as hard links
 - nuttx-patches moved into nuttx/ and apps/ commits
 - nuttx-configs moved into this repo under configs/
 - no more nuttx-export
 - nuttx and apps forks currently on bitbucket - https://bitbucket.org/account/user/px4/projects/NUT
Being closer to upstream NuttX development might encourage more collaboration.

PX4 PR - https://github.com/PX4/Firmware/pull/7397

**Comment by lukegluke** [comment]
Hi, @dagar 

I'm really interesting in px4 nuttx to be closer to upstream NuttX.
I'm developing on Windows (yes, I know that this is not the good choice :) with help of corresponding px4 toolchain for windos. I've already many times successfully built px4 firmware and its modifications from master branch.
I've tried to build px4 firmware from your nuttx-cmake branch, but encountered on error:
`failed to create symbolic link '[...absolute path...]/PX4Firmware/build_px4fmu-v4_default/NuttX/nuttx/PX4_Config.mk': No error`
I'm not an expert in cmake but as I understand from [searching](http://cmake.3232098.n2.nabble.com/cmake-E-create-symlink-for-Windows-td4151271.html) cmake for windows doesn't support "-E create_symlink" command.
I understand that this is not popular OS for developing, but could you please correct this issue. I don't see whole picture, using copy instead of symlink will be suitable?
Many thanks in advance!

update: when I change symlinks to copy operations then in further building got:
```
make[6]: *** [board] Error 1
make[5]: *** [dirlinks] Error 2
make[4]: *** [dirlinks] Error 2
make[3]: *** [NuttX/nuttx/include/nuttx/version.h] Error 2
make[2]: *** [NuttX/CMakeFiles/nuttx_context.dir/all] Error 2
make[1]: *** [all] Error 2
```

**Comment by dagar** [comment]
@lukegluke thanks for testing. If this is a viable path forward we can do a pass to fix the windows issues. C

What do you think about using Windows 10 bash/ubuntu instead of the PX4 tools? I've found that to be faster and ultimately easier. Plus PX4 tools would no longer need to exist (it's frequently out of date).

**Comment by lukegluke** [comment]
Thanks for suggestions. I have Windows 7 and don't have plans to update to Win10. For now it's easier for me to use virtual machine with Ubuntu. Installing it right now.

**Comment by lukegluke** [comment]
@dagar 
By the way, if suddenly useful, I build nuttx-cmake px4fmu-v2 on ubuntu through virtualbox both in bash and qt creator.
Also in Windows 10 there is only bash, so there will be no way to develop through IDE right?

If you will allow, I ask here: according to docs qt creator is only officially supported IDE (and I want to use it too), but in contrast with eclipse project when I open CMakeLists.txt in qt project looks "trimmed" - it doesn't show in project list many source, for example orb messages, ROMFS. I wonder why?
Thanks for info again.
